FROM elixir:1.4.2

ENV VERSION=2017-06-06
ENV DEBIAN_FRONTEND=noninteractive

# Install hex
RUN mix local.hex --force

RUN mix local.rebar --force

# Install NodeJS 6.x and the NPM
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y -q nodejs

# Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Install inotify-tools (for hot realoading), yarn, imagemagick
RUN apt-get update && apt-get install -y yarn imagemagick inotify-tools libnotify-bin

ENV APP_HOME /opt/luggage
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
